## Creating Numpy Arrays

### 1. Using np.array() // 1D and 2D
### 2. Using np.zeros/ ones/ empty/ random()
### 3. Using np.arange()
### 4. Using np.linspace()
### 5. Using Copy()
### 6. Using Identity()


## Method 1 - N-d array

In [1]:
## Creating n - d array

import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## Method 2 - zeros/ones/...

In [6]:
arr3 = np.zeros((2,3))  ## (()) - first bracket is for zero()
                                # - second one is for (size)

In [7]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])